#!/usr/bin/env ruby
# encoding: UTF-8

require File.expand_path('../../config/environment',  __FILE__)

Athlete.order(:nachname, :vorname).each do |athlete|
  puts "#{athlete.nachname} #{athlete.vorname}"
end
