#!/usr/bin/env ruby
# encoding: UTF-8

require File.expand_path('../../config/environment',  __FILE__)

Athlete.all.each do |athlete|
  if Athlete.where(:startnr => athlete.startnr).count > 1 then
    puts "Startnr #{athlete.startnr} mehrmals vergeben!"
  end
end
