#!/usr/bin/env ruby

require 'csv'
require File.expand_path('../../config/environment',  __FILE__)

CSV.open("export.csv", "wb") do |csv|
  Category.all.each do |category|

    csv << [ category.titel ]
    csv << [ "Rang", "Nachname", "Vorname", "PLZ", "Ort", "Strasse", "Verein", "Zeit" ]

    category.athletes.select do |x|
      x.zeit != nil
    end.each_with_index do |x, i|
      gemeinde = x.gemeinde.split(" ")
      csv << [ (i + 1).to_s, x.nachname, x.vorname, gemeinde[0], gemeinde[1], x.strasse, x.verein, x.zeit, "" ]
    end
  end
end
