#!/usr/bin/env ruby
# encoding: UTF-8

require 'csv'
require File.expand_path('../../config/environment',  __FILE__)

Athlete.all.each(&:delete)


CSV.foreach(ARGV[0], { headers: true }) do |row|
  if row.field('id') != nil then

    h = {}
    h[:gemeinde]   = row.field 'ort'
    h[:geschlecht] = row.field('Gesch') == 'w' ? 'Mädchen' : 'Knabe'
    h[:jahrgang]   = row.field 'Geb-Jahr'
    h[:lizenz]     = row.field 'Lizenz-Nr.'
    h[:nachname]   = row.field 'nachname'
    h[:vorname]    = row.field 'vorname'
    h[:verein]     = row.field 'verein'
    h[:strasse]    = row.field 'adresse'
    h[:startnr]    = 0

    Athlete.new(h).save!
  end
end

startnr = 1
Category.all.each do |cat|
  puts "Category #{cat.name}: StartNr block #{startnr}"

  cat.athletes.each do |athlete|
    athlete.update_attribute(:startnr, startnr)
    startnr = startnr + 1
  end

  startnr = ((startnr / 10).floor + 1) * 10
end


Athlete.all.each do |athlete|
  if Athlete.where(:startnr => athlete.startnr).count > 1 then
    puts "Startnr #{athlete.startnr} mehrmals vergeben!"
  end
end
