#!/usr/bin/env ruby

require 'csv'
require File.expand_path('../../config/environment',  __FILE__)

Athlete.all.each(&:delete)

CSV.foreach(ARGV[0], { headers: true }) do |row|
  row.delete('kategorie')
  Athlete.new(row.to_hash).save!
end
